### ISSUE TITLE
Ask communitiy for feedback?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/good-enough-practices-in-scientific-computing#133]
Please vote by commenting on this issue, or by using the emoji "thumbs up" or "thumbs down".

**Comment by jennybc** [comment]
I would still like to have a crack at the remaining sections. It will go way faster than data management, for which I felt very responsible. But then YES.

**Comment by jkitzes** [comment]
I'm somewhat ambivalent - always good to get feedback of course, but on the other hand I think that the current manuscript is very much "good enough" and that additional feedback is more likely to lead to us making changes that take us in circles rather than moving the paper forward (and I suspect any forward motion would be minor). But you never know...

**Comment by jennybc** [comment]
@jkitzes has a good point. We are already a large author group and have been getting community input along the way.

**Comment by kcranston** [comment]
Contrary to my usual 'yes, of course!' stance on community input, I lean towards not sending this out for feedback. We have had input along the way, and I worry about opening up a can of worms about 'best' vs 'good enough' practices (i.e. arguments about including all of the practices that much of the SWC community uses every day but are too high a bar for newcomers).

**Comment by beroe** [comment]
Karen has a good point (and +1 for slipping "newcomer" in there)

**Comment by jennybc** [comment]
I hereby retract my original 👍. As a compromise, do we perhaps want to ask 1 or 2 specific individuals to read the whole thing with fresh eyes?

**Comment by gvwilson** [comment]
It appears the consensus is :-1:, so I'll close this.
