### ISSUE TITLE
references for Software section

### ISSUE THREAD

**Issue by kcranston** [swcarpentry/good-enough-practices-in-scientific-computing#170]
One reviewer points out that there are thousands of books and articles on how to write / structure source code and that we should be clear that this section reiterates existing advice. I am soliciting your favourite references for writing, organizing, and sharing scripts and programs.

**Comment by jkitzes** [comment]
Off the top of my head, I would list *Clean Code* and *Beautiful Code*, then maybe a book on software design patterns (no particular favorite).

**Comment by jennybc** [comment]
The Pragmatic Programmer?

**Comment by lexnederbragt** [comment]
+1 to Clean Code (https://www.amazon.com/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882), but not based on personal experience, only because it is used by a bioinformaticians group here.

**Comment by gvwilson** [comment]
I'm less enamored of *Pragmatic Programmer* and *Clean Code* than I was a decade ago, primarily because their authors have often been in the "evidence? we don't need no stinkin' evidence!" camp.  And while I'm fond of *Beautiful Code*, I think it's too wide-ranging for our intended audience.

The one I keep coming back to is *[Code Complete](https://www.amazon.com/Code-Complete-Practical-Handbook-Construction/dp/0735619670/)* - it's well organized, and full of references to empirical studies (rather than just the author's opinions).  It is pretty thick, though, so *Pragmatic Programmer* as a smaller second choice maybe?

**Comment by tracykteal** [comment]
+1 for _Pragmatic Programmer_. @ctb and @ethanwhite might also have thoughts.

**Comment by gvwilson** [comment]
Reference to PragProg now included.

**Comment by kcranston** [comment]
Re-opening this, because we still have a [comment in the ms](https://github.com/swcarpentry/good-enough-practices-in-scientific-computing/blob/gh-pages/good-enough-practices-for-scientific-computing.tex#L449) requesting refs. I see the hunt reference attached to the specific recommendation in the previous sentence, but reviewer 1 is specifically asking for references to some of the "thousands of books and millions of articles on the subject", i.e. for our phrase "Much has been written on this topic..." and I don't think the single ref to hunt is sufficient.

**Comment by jkitzes** [comment]
@kcranston I take it we can close this one now given #189?
