### ISSUE TITLE
Keep detailed analysis of double recommendation for manuscripts?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/good-enough-practices-in-scientific-computing#180]
See line 1205++ in manuscript - please add a comment to this issue saying whether you want to keep the detailed description or drop it.

**Comment by kcranston** [comment]
If the audience for this manuscript is the researchers who need to change their current practices to Good Enough Practices, then I think deleting the detailed description makes sense. The main purpose of this section seems to be convincing computational researchers who are well beyond 'good enough'.

Therefore, I vote for dropping it.

**Comment by jkitzes** [comment]
I don't have a strong feeling either way, but given (if I'm remembering correctly) that the reviewers didn't call out this section specifically, I'm inclined to leave it in. Agree that it reads differently, but also agree that there's a subset of readers who will find it useful.

So mark me as a +0.25 for leaving in.

**Comment by lexnederbragt** [comment]
I see the point, and wouldn't object too strongly when it goes, as long as there remains a sentence or two explaining that, paralleling the software section, we recommend two approaches. But I also agree with @jkitzes that should be careful changing a lot beyond what the reviewers ask for. So in all I'm also +0.25 for leaving it in.

**Comment by tracykteal** [comment]
I think it speaks to tone. In other areas we do say that we primarily use something (like git) but doesn't come across in the same way as here. In my edit I tried to basically leave the recommendation but address the tone. Maybe we can hit that same middle ground with a different introduction before the quotes. Suggestion here:

``
Initially we recommended always using plain text in version control to manage manuscripts, but upon broader circulation, realized the overhead in tools associated with this recommendation created a significant barrier to entry. Similarly the purpose of version control (being able to both track and reproduce changes) is different from that of writing manuscripts, where tracking changes is the important element.

For example, Stephen Turner wrote:                            

%\begin{quote}                                                                  
%{\ldots}try to explain the notion of compiling a document to an                
%overworked physician you collaborate with. Oh, but before that, you            
%have to explain the difference between plain text and word                     
%processing. And text editors. And markdown/LaTeX compilers. And                
%BiBTeX. And Git. And GitHub. Etc. Meanwhile he/she is getting paged            
%from the OR{\ldots}                                                            

%{\ldots}as much as we want to convince ourselves otherwise, when you           
%have to collaborate with those outside the scientific computing                
%bubble, the barrier to collaborating on papers in this framework is            
%simply too high to overcome. Good intentions aside, it always comes            
%down to ``just give me a Word document with tracked changes,'' or              
%similar.                                                                       
%\end{quote}                                                                    

%Similarly, Arjun Raj said in \withurl{a blog                                   
%  post}{http://rajlaboratory.blogspot.ca/2016/03/from-over-reproducibility-to.\
html}:                                                                          

%\begin{quote}                                                                  
%Google Docs excels at easy sharing, collaboration, simultaneous                
%editing, commenting and reply-to-commenting. Sure, one can approximate         
%these using text-based systems and version control. The question is            
%why anyone would like to{\ldots}                                               

%The goal of reproducible research is to make sure one                          
%can{\dots}reproduce{\ldots}computational analyses. The goal of version         
%control is to track changes to source code. These are fundamentally            
%distinct goals, and while there is some overlap, version control is            
%merely a tool to help achieve that, and comes with so much overhead            
%and baggage that it is often not worth the effort.                             
%\end{quote}

**Comment by tracykteal** [comment]
I also just noticed we don't have anything about Dropbox in the Manuscripts section. Word documents with tracked changes in DropBox is a pretty standard practice, and DropBox does let you roll back to previous versions.

**Comment by jkitzes** [comment]
I'm happy with any of the approaches raised above, personally. @gvwilson may jump in on Word+Dropbox, but I'd not that we eliminated the idea of suggesting Word fairly early on in the process (I had actually raised it then as well, but we decided not to go in that direction). This section was/is relatively contentious overall, relative to the rest of the paper, and I would lean away from making a substantial change (like "allowing" Word) at this stage.
