### ISSUE TITLE
Comment format?

### ISSUE THREAD

**Issue by beroe** [swcarpentry/good-enough-practices-in-scientific-computing#75]
Is there a preferred format for in-line notes in this document.  Stack overflowing for "Comments in Markdown" leads to many non-universal optionss.

**Comment by gvwilson** [comment]
Markdown doesn't have a standard comment syntax, so please just throw in 
lines starting with "FIXME:".

**Comment by jkitzes** [comment]
Presuming that this document will either end up as HTML itself or submitted to a journal that require something like Word (which probably means using pandoc for conversion), I think HTML format comments would make the most sense, if we wanted to go that way.

**Comment by gvwilson** [comment]
I think the question is about what we can put in the doc now (when it's 
in Markdown) as comments - as far as I can tell, there isn't a standard 
commenting format.

**Comment by jkitzes** [comment]
Yes, I did follow that, and agreed about the lack of a standard. I was just suggesting that if we wanted to pick one format to use at this point in the Markdown doc, HTML would make sense, since pandoc will consider it a comment and hence ignore it when converting to Word, pdf, or HTML (and I imagine we are likely to have to perform this conversion at some point before submission).

**Comment by beroe** [comment]
We used `<!-- comment -->` in a collaborative document that was piped through Pandoc and it seemed to work OK. Doesn't get rendered by GitHub AFAICT, but that is OK, I think?
I can use FIXME: as well. I was thinking of inline comments, but they don't have to be so...
